// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmsIaZlJCsmlLyAC2SONg0Nvta-NhXkCo',
    appId: '1:58158833203:web:675e4bfc211a52b2678d46',
    messagingSenderId: '58158833203',
    projectId: 'flutter-app-d644e',
    authDomain: 'flutter-app-d644e.firebaseapp.com',
    storageBucket: 'flutter-app-d644e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4AOZxmM8NCU3UJ-j6c_jT0hBIWfejY5Y',
    appId: '1:58158833203:android:b63a88beb852bc76678d46',
    messagingSenderId: '58158833203',
    projectId: 'flutter-app-d644e',
    storageBucket: 'flutter-app-d644e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBTWIhHxcN-Ebaei83g-UoBors6mWxQw4',
    appId: '1:58158833203:ios:b466072150c04511678d46',
    messagingSenderId: '58158833203',
    projectId: 'flutter-app-d644e',
    storageBucket: 'flutter-app-d644e.firebasestorage.app',
    iosBundleId: 'com.example.playground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBTWIhHxcN-Ebaei83g-UoBors6mWxQw4',
    appId: '1:58158833203:ios:b466072150c04511678d46',
    messagingSenderId: '58158833203',
    projectId: 'flutter-app-d644e',
    storageBucket: 'flutter-app-d644e.firebasestorage.app',
    iosBundleId: 'com.example.playground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmsIaZlJCsmlLyAC2SONg0Nvta-NhXkCo',
    appId: '1:58158833203:web:399e6268c8f66c8d678d46',
    messagingSenderId: '58158833203',
    projectId: 'flutter-app-d644e',
    authDomain: 'flutter-app-d644e.firebaseapp.com',
    storageBucket: 'flutter-app-d644e.firebasestorage.app',
  );

}